### ISSUE TITLE
Wireshark Files

### ISSUE THREAD

**Issue by PaulderGraph** [dend/decksurf-docs#1]
Hello, I really admire your Work of the DeckSurf SDK. I want to make a Project that is the Counterpiece to your Work. It will be an Open Source Stream Deck. Can you Put the wireshark capture Files in the Documentation or Tell me where I can find them.

Thanks, 
Paul Graf

**Comment by dend** [comment]
@PaulderGraph unfortunately I am not able to share my WireShark files for privacy reasons. That said, you can learn more about my work in this domain here: https://den.dev/blog/reverse-engineering-stream-deck/

**Comment by derGraph** [comment]
Thats unfortunate,
Can you Just send me Screenshots of the first few Packets?
